day01:
	gcc -o day01 day01.c
	./day01 ../Rust/problems/inputs/day01.in.txt

day02:
	gcc -o day02 day02.c
	./day02 ../Rust/problems/inputs/day02.in.txt

day06:
	gcc -o day06 day06.c
	./day06 ../Rust/problems/inputs/day06.in.txt

.PHONY: day01 day02 day06
