day01:
	gcc -o day01 day01.c
	./day01 ../Rust/problems/inputs/day01.in.txt

day02:
	gcc -o day02 day02.c
	./day02 ../Rust/problems/inputs/day02.in.txt

day03:
	gcc -o day03 day03.c
	./day03 ../Rust/problems/inputs/day03.in.txt

.PHONY: day01 day02 day03
