day01:
	gcc -o day01 day01.c
	./day01 ../.inputs/day01.txt
day02:
	gcc -o day02 day02.c
	./day02 ../.inputs/day02.txt
day03:
	gcc -o day03 day03.c
	./day03 ../.inputs/day03.txt
day05:
	gcc -o day05 day05.c
	./day05 ../.inputs/day05.txt

.PHONY: day01 day02 day03 day05
